server:
  port: 8181
management:
  info:
    build:
      enabled: true
    git:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notedb
  mail:
    host: smtp.mailtrap.io
    password: 40cbc35fed2157
    port: 2525
    username: 08281e9850c073

mailtrap:
  inbox: 69f4d8bdce-5254f8@inbox.mailtrap.io
