server:
  port: 8282
management:
  info:
    build:
      enabled: true
    git:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
documentation:
  baseurl: http://localhost
  swagger:
    services:
      - name: note
        url: ${documentation.baseurl}:8080/v2/api-docs?group=note-v1
        version: 2.0
      - name: email
        url: ${documentation.baseurl}:8181/v2/api-docs?group=email-v1
        version: 2.0
